name: tests

on:
  push:
  pull_request:

jobs:
  windows-tests:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Run unit tests
        shell: pwsh
        run: python -m unittest discover tests
